### ISSUE TITLE
Trying to understand the code, I get a blank page in browser

### ISSUE THREAD

**Issue by WakeReality** [ramiroaisen/raven-webmail#49]
I'm starting it from "npm run dev" then opening the port on a browser. The loading icon appears and is unloaded after 2 seconds.

The code has __layout.svelte requesting /api/pages/layout

Is there a sveltekit route named "/api/? I can't find it.

When developing, do you have to start the server manually or is "npm run dev" supposed to start everything?

**Comment by ramiroaisen** [comment]
In dev mode the sveltekit app and the nodejs server run in two different processes and the nodejs app proxies requests to the sveltekit dev server, you are probably opening the sveltekit dev server port instead of the nodejs server port. nevermind the messages you get in the terminal you need to open the port that is specified in the config.toml file

**Comment by ramiroaisen** [comment]
I'll close this issue now, please if you need more help create a new one with more info describing the problem you're facing
